//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5466
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System;
using FortnoxAPILibrary.Connectors;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Account
	{

		private string activeField;

		private string balanceBroughtForwardField;

		private string balanceCarriedForwardField;

		private string costCenterField;

		private AccountConnector.CostCenterSettingsValue costCenterSettingsField;

		private string descriptionField;

		private string numberField;

		private string projectField;

		private AccountConnector.ProjectSettingsValue projectSettingsField;

		private string sRUField;

		private string transactionInformationField;

		private AccountConnector.TransactionInfoSettingsValue transactionInformationSettingsField;

		private string vATCodeField;

		private string yearField;

		private string urlField;

		/// <remarks/>
		public string Active
		{
			get
			{
				return this.activeField;
			}
			set
			{
				this.activeField = value;
			}
		}

		/// <remarks/>
		public string BalanceBroughtForward
		{
			get
			{
				return this.balanceBroughtForwardField;
			}
			set
			{
				this.balanceBroughtForwardField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string BalanceCarriedForward
		{
			get
			{
				return this.balanceCarriedForwardField;
			}
			set
			{
				this.balanceCarriedForwardField = value;
			}
		}

		/// <remarks/>
		public string CostCenter
		{
			get
			{
				return this.costCenterField;
			}
			set
			{
				this.costCenterField = value;
			}
		}

		/// <remarks/>
		public AccountConnector.CostCenterSettingsValue CostCenterSettings
		{
			get
			{
				return this.costCenterSettingsField;
			}
			set
			{
				this.costCenterSettingsField = value;
			}
		}

		/// <remarks/>
		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		public string Number
		{
			get
			{
				return this.numberField;
			}
			set
			{
				this.numberField = value;
			}
		}

		/// <remarks/>
		public string Project
		{
			get
			{
				return this.projectField;
			}
			set
			{
				this.projectField = value;
			}
		}

		/// <remarks/>
		public AccountConnector.ProjectSettingsValue ProjectSettings
		{
			get
			{
				return this.projectSettingsField;
			}
			set
			{
				this.projectSettingsField = value;
			}
		}

		/// <remarks/>
		public string SRU
		{
			get
			{
				return this.sRUField;
			}
			set
			{
				this.sRUField = value;
			}
		}

		/// <remarks/>
		public string TransactionInformation
		{
			get
			{
				return this.transactionInformationField;
			}
			set
			{
				this.transactionInformationField = value;
			}
		}

		/// <remarks/>
		public AccountConnector.TransactionInfoSettingsValue TransactionInformationSettings
		{
			get
			{
				return this.transactionInformationSettingsField;
			}
			set
			{
				this.transactionInformationSettingsField = value;
			}
		}

		/// <remarks/>
		public string VATCode
		{
			get
			{
				return this.vATCodeField;
			}
			set
			{
				this.vATCodeField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string Year
		{
			get
			{
				return this.yearField;
			}
			set
			{
				this.yearField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.ReadOnly(true)]
		public string url
		{
			get
			{
				return this.urlField;
			}
			set
			{
				this.urlField = value;
			}
		}
	}
}
