//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5466
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
using System.ComponentModel;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Articles
	{

		private List<ArticleSubset> articlesSubsetField;

		private string totalResourcesField;

		private string totalPagesField;

		private string currentPageField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("ArticleSubset", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public List<ArticleSubset> ArticleSubset
		{
			get
			{
				return this.articlesSubsetField;
			}
			set
			{
				this.articlesSubsetField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string TotalResources
		{
			get
			{
				return this.totalResourcesField;
			}
			set
			{
				this.totalResourcesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string TotalPages
		{
			get
			{
				return this.totalPagesField;
			}
			set
			{
				this.totalPagesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string CurrentPage
		{
			get
			{
				return this.currentPageField;
			}
			set
			{
				this.currentPageField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ArticleSubset
	{

		private string articleNumberField;

		private string descriptionField;

		private string disposableQuantityField;

		private string eANField;

		private string houseworkField;

		private string purchasePriceField;

		private string quantityInStockField;

		private string reservedQuantityField;

		private string stockPlaceField;

		private string stockValueField;

		private string unitField;

        private string vATField;

		private string webshopArticleField;

		/// <remarks/>
		private string urlField;

	    private string _salesPrice;

	    /// <remarks/>
		public string ArticleNumber
		{
			get
			{
				return this.articleNumberField;
			}
			set
			{
				this.articleNumberField = value;
			}
		}

		/// <remarks/>
		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		public string DisposableQuantity
		{
			get
			{
				return this.disposableQuantityField;
			}
			set
			{
				this.disposableQuantityField = value;
			}
		}

		/// <remarks/>
		public string EAN
		{
			get
			{
				return this.eANField;
			}
			set
			{
				this.eANField = value;
			}
		}

		/// <remarks/>
		public string Housework
		{
			get
			{
				return this.houseworkField;
			}
			set
			{
				this.houseworkField = value;
			}
		}

		/// <remarks/>
		public string PurchasePrice
		{
			get
			{
				return this.purchasePriceField;
			}
			set
			{
				this.purchasePriceField = value;
			}
		}

	    /// <remarks/>
	    [ReadOnly(true)]
	    public string SalesPrice
	    {
	        get
	        {
	            return _salesPrice;
	        }
	        set
	        {
	            _salesPrice = value;
	        }
	    }

	    /// <remarks/>
	    public string QuantityInStock
		{
			get
			{
				return this.quantityInStockField;
			}
			set
			{
				this.quantityInStockField = value;
			}
		}

		/// <remarks/>
		public string ReservedQuantity
		{
			get
			{
				return this.reservedQuantityField;
			}
			set
			{
				this.reservedQuantityField = value;
			}
		}

		/// <remarks/>
		public string StockPlace
		{
			get
			{
				return this.stockPlaceField;
			}
			set
			{
				this.stockPlaceField = value;
			}
		}

		/// <remarks/>
		public string StockValue
		{
			get
			{
				return this.stockValueField;
			}
			set
			{
				this.stockValueField = value;
			}
		}

		/// <remarks/>
		public string Unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

        /// <remarks/>
        public string VAT {
            get {
                return this.vATField;
            }
            set {
                this.vATField = value;
            }
        }

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string url
		{
			get
			{
				return this.urlField;
			}
			set
			{
				this.urlField = value;
			}
		}

		/// <remarks/>
		public string WebshopArticle
		{
			get
			{
				return this.webshopArticleField;
			}
			set
			{
				this.webshopArticleField = value;
			}
		}

	}
}