//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5466
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System;
using System.ComponentModel;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Currency
	{

		private string buyRateField;

		private string codeField;

		private string dateField;

		private string descriptionField;

		private string sellRateField;

		private string unitField;

		private string urlField;

		/// <summary>
		/// <para>The buy rate of the currency</para>
		/// <para>Required:		No</para>
		/// <para>Type:			Float</para>
		/// <para>Permissions:	RW</para>
		/// </summary>
		public string BuyRate
		{
			get
			{
				return this.buyRateField;
			}
			set
			{
				this.buyRateField = value;
			}
		}

		/// <summary>
		/// <para>Code of the currency</para>
		/// <para>Required:		Yes</para>
		/// <para>Limits:		3 chars, A-Z</para>
		/// <para>Type:			String</para>
		/// <para>Permissions:	RW</para>
		/// </summary>
		public string Code
		{
			get
			{
				return this.codeField;
			}
			set
			{
				this.codeField = value;
			}
		}

		/// <summary>
		/// <para>Date of creation</para>
		/// <para>Type:			Date</para>
		/// <para>Permissions:	R</para>
		/// </summary>
		[ReadOnly(true)]
		public string Date
		{
			get
			{
				return this.dateField;
			}
			set
			{
				this.dateField = value;
			}
		}

		/// <summary>
		/// <para>Description of the currency</para>
		/// <para>Required:		No</para>
		/// <para>Type:			Date</para>
		/// <para>Permissions:	R</para>
		/// </summary>
		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <summary>
		/// <para>The sell rate of the currency</para>
		/// <para>Required:		No</para>
		/// <para>Type:			Float</para>
		/// <para>Permissions:	RW</para>
		/// </summary>
		public string SellRate
		{
			get
			{
				return this.sellRateField;
			}
			set
			{
				this.sellRateField = value;
			}
		}

		/// <summary>
		/// <para>The unit of the currency</para>
		/// <para>Required:		No</para>
		/// <para>Type:			Float</para>
		/// <para>Permissions:	RW</para>
		/// </summary>
		public string Unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[ReadOnly(true)]
		public string url
		{
			get
			{
				return this.urlField;
			}
			set
			{
				this.urlField = value;
			}
		}
	}
}


