//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5472
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using FortnoxAPILibrary.Connectors;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class InvoiceAccrual
	{

		private string accrualAccountField;

		private string descriptionField;

		private string endDateField;

		private List<InvoiceAccrualRow> invoiceAccrualRowsField;

		private string invoiceNumberField;

		private InvoiceAccrualConnector.Period? periodField;

		private string revenueAccountField;

		private string startDateField;

		private string timesField;

		private string totalField;

		private string vATIncludedField;

		private string urlField;

		/// <remarks/>
		public string AccrualAccount
		{
			get
			{
				return this.accrualAccountField;
			}
			set
			{
				this.accrualAccountField = value;
			}
		}

		/// <remarks/>
		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		public string EndDate
		{
			get
			{
				return this.endDateField;
			}
			set
			{
				this.endDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("InvoiceAccrualRow", IsNullable = false)]
		public List<InvoiceAccrualRow> InvoiceAccrualRows
		{
			get
			{
				return this.invoiceAccrualRowsField;
			}
			set
			{
				this.invoiceAccrualRowsField = value;
			}
		}

		/// <remarks/>
		public string InvoiceNumber
		{
			get
			{
				return this.invoiceNumberField;
			}
			set
			{
				this.invoiceNumberField = value;
			}
		}

		/// <remarks/>
		public InvoiceAccrualConnector.Period? Period
		{
			get
			{
				return this.periodField;
			}
			set
			{
				this.periodField = value;
			}
		}
        public bool PeriodSpecified => Period != null;

		/// <remarks/>
		public string RevenueAccount
		{
			get
			{
				return this.revenueAccountField;
			}
			set
			{
				this.revenueAccountField = value;
			}
		}

		/// <remarks/>
		public string StartDate
		{
			get
			{
				return this.startDateField;
			}
			set
			{
				this.startDateField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Times
		{
			get
			{
				return this.timesField;
			}
			set
			{
				this.timesField = value;
			}
		}

		/// <remarks/>
		public string Total
		{
			get
			{
				return this.totalField;
			}
			set
			{
				this.totalField = value;
			}
		}

		/// <remarks/>
		public string VATIncluded
		{
			get
			{
				return this.vATIncludedField;
			}
			set
			{
				this.vATIncludedField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.ReadOnly(true)]
		public string url
		{
			get
			{
				return this.urlField;
			}
			set
			{
				this.urlField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class InvoiceAccrualRow
	{

		private string accountField;

		private string costCenterField;

		private string creditField;

		private string debitField;

		private string transactionInformationField;

		private string projectField;

		/// <remarks/>
		public string Account
		{
			get
			{
				return this.accountField;
			}
			set
			{
				this.accountField = value;
			}
		}

		/// <remarks/>
		public string CostCenter
		{
			get
			{
				return this.costCenterField;
			}
			set
			{
				this.costCenterField = value;
			}
		}

		/// <remarks/>
		public string Credit
		{
			get
			{
				return this.creditField;
			}
			set
			{
				this.creditField = value;
			}
		}

		/// <remarks/>
		public string Debit
		{
			get
			{
				return this.debitField;
			}
			set
			{
				this.debitField = value;
			}
		}

		/// <remarks/>
		public string TransactionInformation
		{
			get
			{
				return this.transactionInformationField;
			}
			set
			{
				this.transactionInformationField = value;
			}
		}

		/// <remarks/>
		public string Project
		{
			get
			{
				return this.projectField;
			}
			set
			{
				this.projectField = value;
			}
		}
	}
}