//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5472
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel;
using FortnoxAPILibrary.Connectors;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Invoice
	{

		private string administrationFeeField;

        private string administrationFeeVATField;

		private string address1Field;

		private string address2Field;

		private string balanceField;

		private string basisTaxReductionField;

		private string bookedField;

		private string cancelledField;

		private string cityField;

		private string commentsField;

		private string contributionPercentField;

		private string contributionValueField;

		private string countryField;

		private string costCenterField;

		private string creditField;

		private string currencyField;

		private string currencyRateField;

		private string currencyUnitField;

		private string customerNameField;

		private string customerNumberField;

		private string deliveryAddress1Field;

		private string deliveryAddress2Field;

		private string deliveryCityField;

		private string deliveryCountryField;

		private string deliveryDateField;

		private string deliveryNameField;

		private string deliveryZipCodeField;

		private string documentNumberField;

		private string dueDateField;

		private InvoiceEDIInformation eDIInformationField;

		private InvoiceEmailInformation emailInformationField;

        private string euQuarterlyReportField;

		private string freightField;

        private string freightVATField;

		private string grossField;

		private string houseWorkField;

		private string invoiceDateField;

		private List<InvoiceRow> invoiceRowsField;

		private InvoiceConnector.InvoiceType invoiceTypeField;

		private string languageField;

		private string lastRemindDateField;

		private string netField;

		private string notCompletedField;

		private string oCRField;

		private string offerReferenceField;

		private string orderReferenceField;

		private string organisationNumberField;

		private string ourReferenceField;

		private string phone1Field;

		private string phone2Field;

		private string priceListField;

		private string printTemplateField;

		private string projectField;

		private string remarksField;

		private string remindersField;

		private string roundOffField;

		private string sentField;

		private string taxReductionField;

		private string termsOfDeliveryCodeField;

		private string termsOfPaymentField;

		private string totalField;

		private string totalToPayField;

		private string totalVATField;

		private string externalInvoiceReference1Field;

		private string externalInvoiceReference2Field;

		private string vATIncludedField;

		private string voucherNumberField;

		private string voucherSeriesField;

		private string voucherYearField;

		private string wayOfDeliveryCodeField;

		private string yourOrderNumberField;

		private string yourReferenceField;

		private string zipCodeField;

		private string urlField;

		private string urlTaxReductionListField;

        /// <remarks/>
        public Invoice()
        {
            this.InvoiceRows = new List<InvoiceRow>();
        }

		/// <remarks/>
		public string AdministrationFee
		{
			get
			{
				return this.administrationFeeField;
			}
			set
			{
				this.administrationFeeField = value;
			}
		}

        /// <summary>This field is Read-Only in Fortnox</summary>
        /// [ReadOnly(true)]
        public string AdministrationFeeVAT
        {
            get
            {
                return this.administrationFeeVATField;
            }
            set
            {
                this.administrationFeeVATField = value;
            }
        }

		/// <remarks/>
		public string Address1
		{
			get
			{
				return this.address1Field;
			}
			set
			{
				this.address1Field = value;
			}
		}

		/// <remarks/>
		public string Address2
		{
			get
			{
				return this.address2Field;
			}
			set
			{
				this.address2Field = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Balance
		{
			get
			{
				return this.balanceField;
			}
			set
			{
				this.balanceField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string BasisTaxReduction
		{
			get
			{
				return this.basisTaxReductionField;
			}
			set
			{
				this.basisTaxReductionField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Booked
		{
			get
			{
				return this.bookedField;
			}
			set
			{
				this.bookedField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Cancelled
		{
			get
			{
				return this.cancelledField;
			}
			set
			{
				this.cancelledField = value;
			}
		}

		/// <remarks/>
		public string City
		{
			get
			{
				return this.cityField;
			}
			set
			{
				this.cityField = value;
			}
		}

		/// <remarks/>
		public string Comments
		{
			get
			{
				return this.commentsField;
			}
			set
			{
				this.commentsField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string ContributionPercent
		{
			get
			{
				return this.contributionPercentField;
			}
			set
			{
				this.contributionPercentField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string ContributionValue
		{
			get
			{
				return this.contributionValueField;
			}
			set
			{
				this.contributionValueField = value;
			}
		}

		/// <remarks/>
		public string Country
		{
			get
			{
				return this.countryField;
			}
			set
			{
				this.countryField = value;
			}
		}

		/// <remarks/>
		public string CostCenter
		{
			get
			{
				return this.costCenterField;
			}
			set
			{
				this.costCenterField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Credit
		{
			get
			{
				return this.creditField;
			}
			set
			{
				this.creditField = value;
			}
		}

        /// <summary>This field is Read-Only in Fortnox</summary>
        [ReadOnly(true)]
        public string CreditInvoiceReference { get; set; }

		/// <remarks/>
		public string Currency
		{
			get
			{
				return this.currencyField;
			}
			set
			{
				this.currencyField = value;
			}
		}

		/// <remarks/>
		public string CurrencyRate
		{
			get
			{
				return this.currencyRateField;
			}
			set
			{
				this.currencyRateField = value;
			}
		}

		/// <remarks/>
		public string CurrencyUnit
		{
			get
			{
				return this.currencyUnitField;
			}
			set
			{
				this.currencyUnitField = value;
			}
		}

		/// <remarks/>
		public string CustomerName
		{
			get
			{
				return this.customerNameField;
			}
			set
			{
				this.customerNameField = value;
			}
		}

		/// <remarks/>
		public string CustomerNumber
		{
			get
			{
				return this.customerNumberField;
			}
			set
			{
				this.customerNumberField = value;
			}
		}

		/// <remarks/>
		public string DeliveryAddress1
		{
			get
			{
				return this.deliveryAddress1Field;
			}
			set
			{
				this.deliveryAddress1Field = value;
			}
		}

		/// <remarks/>
		public string DeliveryAddress2
		{
			get
			{
				return this.deliveryAddress2Field;
			}
			set
			{
				this.deliveryAddress2Field = value;
			}
		}

		/// <remarks/>
		public string DeliveryCity
		{
			get
			{
				return this.deliveryCityField;
			}
			set
			{
				this.deliveryCityField = value;
			}
		}

		/// <remarks/>
		public string DeliveryCountry
		{
			get
			{
				return this.deliveryCountryField;
			}
			set
			{
				this.deliveryCountryField = value;
			}
		}

		/// <remarks/>
		public string DeliveryDate
		{
			get
			{
				return this.deliveryDateField;
			}
			set
			{
				this.deliveryDateField = value;
			}
		}

		/// <remarks/>
		public string DeliveryName
		{
			get
			{
				return this.deliveryNameField;
			}
			set
			{
				this.deliveryNameField = value;
			}
		}

		/// <remarks/>
		public string DeliveryZipCode
		{
			get
			{
				return this.deliveryZipCodeField;
			}
			set
			{
				this.deliveryZipCodeField = value;
			}
		}

		/// <remarks/>
		public string DocumentNumber
		{
			get
			{
				return this.documentNumberField;
			}
			set
			{
				this.documentNumberField = value;
			}
		}

		/// <remarks/>
		public string DueDate
		{
			get
			{
				return this.dueDateField;
			}
			set
			{
				this.dueDateField = value;
			}
		}

		/// <remarks/>
		public InvoiceEDIInformation EDIInformation
		{
			get
			{
				return this.eDIInformationField;
			}
			set
			{
				this.eDIInformationField = value;
			}
		}

		/// <remarks/>
		public InvoiceEmailInformation EmailInformation
		{
			get
			{
				return this.emailInformationField;
			}
			set
			{
				this.emailInformationField = value;
			}
		}

        /// <summary>This field is Read-Only in Fortnox</summary>
        public string EUQuarterlyReport
        {
            get
            {
                return this.euQuarterlyReportField;
            }
            set
            {
                this.euQuarterlyReportField = value;
            }
        }

		/// <remarks/>
		public string Freight
		{
			get
			{
				return this.freightField;
			}
			set
			{
				this.freightField = value;
			}
		}

        /// <summary>This field is Read-Only in Fortnox</summary>
        [ReadOnly(true)]
        public string FreightVAT
        {
            get
            {
                return this.freightVATField;
            }
            set
            {
                this.freightVATField = value;
            }
        }

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Gross
		{
			get
			{
				return this.grossField;
			}
			set
			{
				this.grossField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string HouseWork
		{
			get
			{
				return this.houseWorkField;
			}
			set
			{
				this.houseWorkField = value;
			}
		}

		/// <remarks/>
		public string InvoiceDate
		{
			get
			{
				return this.invoiceDateField;
			}
			set
			{
				this.invoiceDateField = value;
			}
		}

        /// <summary>This field is Read-Only in Fortnox</summary>
        [ReadOnly(true)]
        public string InvoiceReference { get; set; }

		/// <remarks/>
		public List<InvoiceRow> InvoiceRows
		{
			get
			{
				return this.invoiceRowsField;
			}
			set
			{
				this.invoiceRowsField = value;
			}
		}

		/// <remarks/>
		public InvoiceConnector.InvoiceType InvoiceType
		{
			get
			{
				return this.invoiceTypeField;
			}
			set
			{
				this.invoiceTypeField = value;
			}
		}

		/// <remarks/>
		public string Language
		{
			get
			{
				return this.languageField;
			}
			set
			{
				this.languageField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string LastRemindDate
		{
			get
			{
				return this.lastRemindDateField;
			}
			set
			{
				this.lastRemindDateField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Net
		{
			get
			{
				return this.netField;
			}
			set
			{
				this.netField = value;
			}
		}

		/// <remarks/>
		public string NotCompleted
		{
			get
			{
				return this.notCompletedField;
			}
			set
			{
				this.notCompletedField = value;
			}
		}

		/// <remarks/>
		public string OCR
		{
			get
			{
				return this.oCRField;
			}
			set
			{
				this.oCRField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string OfferReference
		{
			get
			{
				return this.offerReferenceField;
			}
			set
			{
				this.offerReferenceField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string OrderReference
		{
			get
			{
				return this.orderReferenceField;
			}
			set
			{
				this.orderReferenceField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string OrganisationNumber
		{
			get
			{
				return this.organisationNumberField;
			}
			set
			{
				this.organisationNumberField = value;
			}
		}

		/// <remarks/>
		public string OurReference
		{
			get
			{
				return this.ourReferenceField;
			}
			set
			{
				this.ourReferenceField = value;
			}
		}

		/// <remarks/>
		public string Phone1
		{
			get
			{
				return this.phone1Field;
			}
			set
			{
				this.phone1Field = value;
			}
		}

		/// <remarks/>
		public string Phone2
		{
			get
			{
				return this.phone2Field;
			}
			set
			{
				this.phone2Field = value;
			}
		}

		/// <remarks/>
		public string PriceList
		{
			get
			{
				return this.priceListField;
			}
			set
			{
				this.priceListField = value;
			}
		}

		/// <remarks/>
		public string PrintTemplate
		{
			get
			{
				return this.printTemplateField;
			}
			set
			{
				this.printTemplateField = value;
			}
		}

		/// <remarks/>
		public string Project
		{
			get
			{
				return this.projectField;
			}
			set
			{
				this.projectField = value;
			}
		}

		/// <remarks/>
		public string Remarks
		{
			get
			{
				return this.remarksField;
			}
			set
			{
				this.remarksField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Reminders
		{
			get
			{
				return this.remindersField;
			}
			set
			{
				this.remindersField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string RoundOff
		{
			get
			{
				return this.roundOffField;
			}
			set
			{
				this.roundOffField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Sent
		{
			get
			{
				return this.sentField;
			}
			set
			{
				this.sentField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string TaxReduction
		{
			get
			{
				return this.taxReductionField;
			}
			set
			{
				this.taxReductionField = value;
			}
		}

		/// <remarks/>
		public string TermsOfDelivery
		{
			get
			{
				return this.termsOfDeliveryCodeField;
			}
			set
			{
				this.termsOfDeliveryCodeField = value;
			}
		}

		/// <remarks/>
		public string TermsOfPayment
		{
			get
			{
				return this.termsOfPaymentField;
			}
			set
			{
				this.termsOfPaymentField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Total
		{
			get
			{
				return this.totalField;
			}
			set
			{
				this.totalField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string TotalToPay
		{
			get
			{
				return this.totalToPayField;
			}
			set
			{
				this.totalToPayField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string TotalVAT
		{
			get
			{
				return this.totalVATField;
			}
			set
			{
				this.totalVATField = value;
			}
		}

		/// <remarks/>
		public string ExternalInvoiceReference1
		{
			get
			{
				return this.externalInvoiceReference1Field;
			}
			set
			{
				this.externalInvoiceReference1Field = value;
			}
		}

		/// <remarks/>
		public string ExternalInvoiceReference2
		{
			get
			{
				return this.externalInvoiceReference2Field;
			}
			set
			{
				this.externalInvoiceReference2Field = value;
			}
		}

		/// <remarks/>
		public string VATIncluded
		{
			get
			{
				return this.vATIncludedField;
			}
			set
			{
				this.vATIncludedField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string VoucherNumber
		{
			get
			{
				return this.voucherNumberField;
			}
			set
			{
				this.voucherNumberField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string VoucherSeries
		{
			get
			{
				return this.voucherSeriesField;
			}
			set
			{
				this.voucherSeriesField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string VoucherYear
		{
			get
			{
				return this.voucherYearField;
			}
			set
			{
				this.voucherYearField = value;
			}
		}

		/// <remarks/>
		public string WayOfDelivery
		{
			get
			{
				return this.wayOfDeliveryCodeField;
			}
			set
			{
				this.wayOfDeliveryCodeField = value;
			}
		}

		/// <remarks/>
		public string YourOrderNumber
		{
			get
			{
				return this.yourOrderNumberField;
			}
			set
			{
				this.yourOrderNumberField = value;
			}
		}

		/// <remarks/>
		public string YourReference
		{
			get
			{
				return this.yourReferenceField;
			}
			set
			{
				this.yourReferenceField = value;
			}
		}

		/// <remarks/>
		public string ZipCode
		{
			get
			{
				return this.zipCodeField;
			}
			set
			{
				this.zipCodeField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[ReadOnly(true)]
		public string url
		{
			get
			{
				return this.urlField;
			}
			set
			{
				this.urlField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[ReadOnly(true)]
		public string urlTaxReductionList
		{
			get
			{
				return this.urlTaxReductionListField;
			}
			set
			{
				this.urlTaxReductionListField = value;
			}
		}
    }

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class InvoiceEDIInformation
	{

		private string eDIGlobalLocationNumberField;

		private string eDIGlobalLocationNumberDeliveryField;

		private string eDIInvoiceExtra1Field;

		private string eDIInvoiceExtra2Field;

		private string eDIOurElectronicReferenceField;

		private string eDIYourElectronicReferenceField;

		/// <remarks/>
		public string EDIGlobalLocationNumber
		{
			get
			{
				return this.eDIGlobalLocationNumberField;
			}
			set
			{
				this.eDIGlobalLocationNumberField = value;
			}
		}

		/// <remarks/>
		public string EDIGlobalLocationNumberDelivery
		{
			get
			{
				return this.eDIGlobalLocationNumberDeliveryField;
			}
			set
			{
				this.eDIGlobalLocationNumberDeliveryField = value;
			}
		}

		/// <remarks/>
		public string EDIInvoiceExtra1
		{
			get
			{
				return this.eDIInvoiceExtra1Field;
			}
			set
			{
				this.eDIInvoiceExtra1Field = value;
			}
		}

		/// <remarks/>
		public string EDIInvoiceExtra2
		{
			get
			{
				return this.eDIInvoiceExtra2Field;
			}
			set
			{
				this.eDIInvoiceExtra2Field = value;
			}
		}

		/// <remarks/>
		public string EDIOurElectronicReference
		{
			get
			{
				return this.eDIOurElectronicReferenceField;
			}
			set
			{
				this.eDIOurElectronicReferenceField = value;
			}
		}

		/// <remarks/>
		public string EDIYourElectronicReference
		{
			get
			{
				return this.eDIYourElectronicReferenceField;
			}
			set
			{
				this.eDIYourElectronicReferenceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class InvoiceEmailInformation
	{
		private string emailAddressFromField;

		private string emailAddressToField;

		private string emailAddressCCField;

		private string emailAddressBCCField;

		private string emailSubjectField;

		private string emailBodyField;

		/// <remarks/>
		public string EmailAddressFrom
		{
			get
			{
				return this.emailAddressFromField;
			}
			set
			{
				this.emailAddressFromField = value;
			}
		}

		/// <remarks/>
		public string EmailAddressTo
		{
			get
			{
				return this.emailAddressToField;
			}
			set
			{
				this.emailAddressToField = value;
			}
		}

		/// <remarks/>
		public string EmailAddressCC
		{
			get
			{
				return this.emailAddressCCField;
			}
			set
			{
				this.emailAddressCCField = value;
			}
		}

		/// <remarks/>
		public string EmailAddressBCC
		{
			get
			{
				return this.emailAddressBCCField;
			}
			set
			{
				this.emailAddressBCCField = value;
			}
		}

		/// <remarks/>
		public string EmailSubject
		{
			get
			{
				return this.emailSubjectField;
			}
			set
			{
				this.emailSubjectField = value;
			}
		}

		/// <remarks/>
		public string EmailBody
		{
			get
			{
				return this.emailBodyField;
			}
			set
			{
				this.emailBodyField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class InvoiceRow
	{

		private string accountNumberField;

		private string articleNumberField;

		private string contributionPercentField;

		private string contributionValueField;

		private string costCenterField;

		private string deliveredQuantityField;

		private string descriptionField;

		private string discountField;

		private InvoiceConnector.DiscountType discountTypeField;

		private string houseWorkField;

        private string priceField;

        private string priceExcludingVatField;

		private string projectField;

        private string totalField;

        private string totalExcludingVatField;

		private string unitField;

		private string vATField;

	    private string noxFinansField;

	    /// <remarks/>
		public string AccountNumber
		{
			get
			{
				return this.accountNumberField;
			}
			set
			{
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		public string ArticleNumber
		{
			get
			{
				return this.articleNumberField;
			}
			set
			{
				this.articleNumberField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string ContributionPercent
		{
			get
			{
				return this.contributionPercentField;
			}
			set
			{
				this.contributionPercentField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string ContributionValue
		{
			get
			{
				return this.contributionValueField;
			}
			set
			{
				this.contributionValueField = value;
			}
		}

		/// <remarks/>
		public string CostCenter
		{
			get
			{
				return this.costCenterField;
			}
			set
			{
				this.costCenterField = value;
			}
		}

		/// <remarks/>
		public string DeliveredQuantity
		{
			get
			{
				return this.deliveredQuantityField;
			}
			set
			{
				this.deliveredQuantityField = value;
			}
		}

		/// <remarks/>
		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		public string Discount
		{
			get
			{
				return this.discountField;
			}
			set
			{
				this.discountField = value;
			}
		}

		/// <remarks/>
		public InvoiceConnector.DiscountType DiscountType
		{
			get
			{
				return this.discountTypeField;
			}
			set
			{
				this.discountTypeField = value;
			}
		}

		/// <remarks/>
		public string HouseWork
		{
			get
			{
				return this.houseWorkField;
			}
			set
			{
				this.houseWorkField = value;
			}
		}

        /// <remarks/>
        public string HouseWorkHoursToReport{ get; set; }

        /// <remarks/>
        public string HouseWorkType { get; set; }

	    /// <remarks/>
	    [ReadOnly(true)]
	    public string NoxFinans
	    {
	        get
	        {
	            return noxFinansField;
	        }
	        set
	        {
	            noxFinansField = value;
	        }
	    }

	    /// <remarks/>
	    public string Price
		{
			get
			{
				return this.priceField;
			}
			set
			{
				this.priceField = value;
			}
		}

        /// <remarks/>
        [ReadOnly(true)]
        public string PriceExcludingVAT
        {
            get
            {
                return priceExcludingVatField;
            }
            set
            {
                priceExcludingVatField = value;
            }
        }

		/// <remarks/>
		public string Project
		{
			get
			{
				return this.projectField;
			}
			set
			{
				this.projectField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string Total
		{
			get
			{
				return this.totalField;
			}
			set
			{
				this.totalField = value;
			}
		}

        /// <remarks/>
        [ReadOnly(true)]
        public string TotalExcludingVAT
        {
            get
            {
                return totalExcludingVatField;
            }
            set
            {
                totalExcludingVatField = value;
            }
        }

		/// <remarks/>
		public string Unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <remarks/>
		public string VAT
		{
			get
			{
				return this.vATField;
			}
			set
			{
				this.vATField = value;
			}
		}
	}
}