//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5466
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
using System;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Orders
	{

		private List<OrderSubset> orderSubsetField;

		private string totalResourcesField;

		private string totalPagesField;

		private string currentPageField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("OrderSubset", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public List<OrderSubset> OrderSubset
		{
			get
			{
				return this.orderSubsetField;
			}
			set
			{
				this.orderSubsetField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string TotalResources
		{
			get
			{
				return this.totalResourcesField;
			}
			set
			{
				this.totalResourcesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string TotalPages
		{
			get
			{
				return this.totalPagesField;
			}
			set
			{
				this.totalPagesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string CurrentPage
		{
			get
			{
				return this.currentPageField;
			}
			set
			{
				this.currentPageField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class OrderSubset
	{
		private string cancelledField;

		private string currencyField;

		private string customerNameField;

		private string customerNumberField;

		private string deliveryDateField;

		private string documentNumberField;

		private string externalInvoiceReference1Field;

		private string externalInvoiceReference2Field;

		private string orderDateField;

		private string projectField;

		private string sentField;

		private string totalField;

		private string urlField;

		/// <remarks/>
		public string Cancelled
		{
			get
			{
				return this.cancelledField;
			}
			set
			{
				this.cancelledField = value;
			}
		}

		/// <remarks/>
		public string Currency
		{
			get
			{
				return this.currencyField;
			}
			set
			{
				this.currencyField = value;
			}
		}

		/// <remarks/>
		public string CustomerName
		{
			get
			{
				return this.customerNameField;
			}
			set
			{
				this.customerNameField = value;
			}
		}

		/// <remarks/>
		public string CustomerNumber
		{
			get
			{
				return this.customerNumberField;
			}
			set
			{
				this.customerNumberField = value;
			}
		}

		/// <remarks/>
		public string DeliveryDate
		{
			get
			{
				return this.deliveryDateField;
			}
			set
			{
				this.deliveryDateField = value;
			}
		}

		/// <remarks/>
		public string DocumentNumber
		{
			get
			{
				return this.documentNumberField;
			}
			set
			{
				this.documentNumberField = value;
			}
		}

		/// <remarks/>
		public string ExternalInvoiceReference1
		{
			get
			{
				return this.externalInvoiceReference1Field;
			}
			set
			{
				this.externalInvoiceReference1Field = value;
			}
		}

		/// <remarks/>
		public string ExternalInvoiceReference2
		{
			get
			{
				return this.externalInvoiceReference2Field;
			}
			set
			{
				this.externalInvoiceReference2Field = value;
			}
		}

		/// <remarks/>
		public string OrderDate
		{
			get
			{
				return this.orderDateField;
			}
			set
			{
				this.orderDateField = value;
			}
		}

		/// <remarks/>
		public string Project
		{
			get
			{
				return this.projectField;
			}
			set
			{
				this.projectField = value;
			}
		}

		/// <remarks/>
		public string Sent
		{
			get
			{
				return this.sentField;
			}
			set
			{
				this.sentField = value;
			}
		}

		/// <remarks/>
		public string Total
		{
			get
			{
				return this.totalField;
			}
			set
			{
				this.totalField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string url
		{
			get
			{
				return this.urlField;
			}
			set
			{
				this.urlField = value;
			}
		}
	}
}