//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5472
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using FortnoxAPILibrary.Connectors;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PreDefinedVoucherSeries {

	private PreDefinedVoucherSeriesConnector.PreDefinedVoucherSeriesName nameField;
    
    private string voucherSeriesField;
    
    private string urlField;

	/// <summary>This field is Read-Only in Fortnox</summary>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	[System.ComponentModel.ReadOnly(true)]
	public PreDefinedVoucherSeriesConnector.PreDefinedVoucherSeriesName Name
	{
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string VoucherSeries {
        get {
            return this.voucherSeriesField;
        }
        set {
            this.voucherSeriesField = value;
        }
    }

	/// <summary>This field is Read-Only in Fortnox</summary>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	[System.ComponentModel.ReadOnly(true)]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
}
