//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5472
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class SieSummary
	{

		private string accountsField;

		private string contactNameField;

		private string contactDeliveryAddressField;

		private string contactMailingAddressField;

		private string contactPhoneField;

		private string costCentersField;

		private string dateOfGenerationField;

		private string extentField;

		private string incomingBalancesField;

		private string projectsField;

		private string termBudgetsField;

		private string typeOfSieField;

		private string usedAccountsField;

		private string usedCostCentersField;

		private string usedProjectsField;

		private string verificationsField;

		private List<VerificationInterval> verificationsIntervalsField;

		/// <remarks/>
		public string Accounts
		{
			get
			{
				return this.accountsField;
			}
			set
			{
				this.accountsField = value;
			}
		}

		/// <remarks/>
		public string ContactName
		{
			get
			{
				return this.contactNameField;
			}
			set
			{
				this.contactNameField = value;
			}
		}

		/// <remarks/>
		public string ContactDeliveryAddress
		{
			get
			{
				return this.contactDeliveryAddressField;
			}
			set
			{
				this.contactDeliveryAddressField = value;
			}
		}

		/// <remarks/>
		public string ContactMailingAddress
		{
			get
			{
				return this.contactMailingAddressField;
			}
			set
			{
				this.contactMailingAddressField = value;
			}
		}

		/// <remarks/>
		public string ContactPhone
		{
			get
			{
				return this.contactPhoneField;
			}
			set
			{
				this.contactPhoneField = value;
			}
		}

		/// <remarks/>
		public string CostCenters
		{
			get
			{
				return this.costCentersField;
			}
			set
			{
				this.costCentersField = value;
			}
		}

		/// <remarks/>
		public string DateOfGeneration
		{
			get
			{
				return this.dateOfGenerationField;
			}
			set
			{
				this.dateOfGenerationField = value;
			}
		}

		/// <remarks/>
		public string Extent
		{
			get
			{
				return this.extentField;
			}
			set
			{
				this.extentField = value;
			}
		}

		/// <remarks/>
		public string IncomingBalances
		{
			get
			{
				return this.incomingBalancesField;
			}
			set
			{
				this.incomingBalancesField = value;
			}
		}

		/// <remarks/>
		public string Projects
		{
			get
			{
				return this.projectsField;
			}
			set
			{
				this.projectsField = value;
			}
		}

		/// <remarks/>
		public string TermBudgets
		{
			get
			{
				return this.termBudgetsField;
			}
			set
			{
				this.termBudgetsField = value;
			}
		}

		/// <remarks/>
		public string TypeOfSie
		{
			get
			{
				return this.typeOfSieField;
			}
			set
			{
				this.typeOfSieField = value;
			}
		}

		/// <remarks/>
		public string UsedAccounts
		{
			get
			{
				return this.usedAccountsField;
			}
			set
			{
				this.usedAccountsField = value;
			}
		}

		/// <remarks/>
		public string UsedCostCenters
		{
			get
			{
				return this.usedCostCentersField;
			}
			set
			{
				this.usedCostCentersField = value;
			}
		}

		/// <remarks/>
		public string UsedProjects
		{
			get
			{
				return this.usedProjectsField;
			}
			set
			{
				this.usedProjectsField = value;
			}
		}

		/// <remarks/>
		public string Verifications
		{
			get
			{
				return this.verificationsField;
			}
			set
			{
				this.verificationsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("VerificationInterval", IsNullable = false)]
		public List<VerificationInterval> VerificationsIntervals
		{
			get
			{
				return this.verificationsIntervalsField;
			}
			set
			{
				this.verificationsIntervalsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class VerificationInterval
	{

		private string firstField;

		private string lastField;

		private string seriesField;

		/// <remarks/>
		public string First
		{
			get
			{
				return this.firstField;
			}
			set
			{
				this.firstField = value;
			}
		}

		/// <remarks/>
		public string Last
		{
			get
			{
				return this.lastField;
			}
			set
			{
				this.lastField = value;
			}
		}

		/// <remarks/>
		public string Series
		{
			get
			{
				return this.seriesField;
			}
			set
			{
				this.seriesField = value;
			}
		}
	}
}