//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5466
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Supplier
	{
		private string activeField;

		private string address1Field;

		private string address2Field;

		private string bankField;

		private string bankAccountNumberField;

		private string bgField;

		private string bICField;

		private string branchCodeField;

		private string cityField;

		private string clearingNumberField;

		private string commentsField;

		private string costCenterField;

		private string countryField;

		private string countryCodeField;

		private string currencyField;

		private string disablePaymentFileField;

		private string emailField;

		private string faxField;

		private string iBANField;

		private string nameField;

		private string organisationNumberField;

		private string ourReferenceField;

		private string ourCustomerNumberField;

		private string pgField;

		private string phone1Field;

		private string phone2Field;

		private string preDefinedAccountField;

		private string projectField;

		private string supplierNumberField;

		private string termsOfPaymentField;

		private string vATNumberField;

		private string visitingAddressField;

		private string visitingCityField;

		private string visitingCountryField;

		private string visitingCountryCodeField;

		private string vistingZipCodeField;

		private string workPlaceField;

		private string wWWField;

		private string yourReferenceField;

		private string zipCodeField;

		private string urlField;

		/// <remarks/>
		public string Address1
		{
			get
			{
				return this.address1Field;
			}
			set
			{
				this.address1Field = value;
			}
		}

		/// <remarks/>
		public string Active
		{
			get
			{
				return this.activeField;
			}
			set
			{
				this.activeField = value;
			}
		}

		/// <remarks/>
		public string Address2
		{
			get
			{
				return this.address2Field;
			}
			set
			{
				this.address2Field = value;
			}
		}

		/// <remarks/>
		public string Bank
		{
			get
			{
				return this.bankField;
			}
			set
			{
				this.bankField = value;
			}
		}

		/// <remarks/>
		public string BankAccountNumber
		{
			get
			{
				return this.bankAccountNumberField;
			}
			set
			{
				this.bankAccountNumberField = value;
			}
		}

		/// <remarks/>
		public string BG
		{
			get
			{
				return this.bgField;
			}
			set
			{
				this.bgField = value;
			}
		}

		/// <remarks/>
		public string BIC
		{
			get
			{
				return this.bICField;
			}
			set
			{
				this.bICField = value;
			}
		}

		/// <remarks/>
		public string BranchCode
		{
			get
			{
				return this.branchCodeField;
			}
			set
			{
				this.branchCodeField = value;
			}
		}

		/// <remarks/>
		public string City
		{
			get
			{
				return this.cityField;
			}
			set
			{
				this.cityField = value;
			}
		}

		/// <remarks/>
		public string ClearingNumber
		{
			get
			{
				return this.clearingNumberField;
			}
			set
			{
				this.clearingNumberField = value;
			}
		}

		/// <remarks/>
		public string Comments
		{
			get
			{
				return this.commentsField;
			}
			set
			{
				this.commentsField = value;
			}
		}

		/// <remarks/>
		public string CostCenter
		{
			get
			{
				return this.costCenterField;
			}
			set
			{
				this.costCenterField = value;
			}
		}

        /// <summary>This field is Read-Only in Fortnox</summary>
        [System.ComponentModel.ReadOnly(true)]
		public string Country
		{
			get
			{
				return this.countryField;
			}
			set
			{
				this.countryField = value;
			}
		}

		/// <remarks/>
		public string CountryCode
		{
			get
			{
				return this.countryCodeField;
			}
			set
			{
				this.countryCodeField = value;
			}
		}

		/// <remarks/>
		public string Currency
		{
			get
			{
				return this.currencyField;
			}
			set
			{
				this.currencyField = value;
			}
		}

		/// <remarks/>
		public string DisablePaymentFile
		{
			get
			{
				return this.disablePaymentFileField;
			}
			set
			{
				this.disablePaymentFileField = value;
			}
		}

		/// <remarks/>
		public string Email
		{
			get
			{
				return this.emailField;
			}
			set
			{
				this.emailField = value;
			}
		}

		/// <remarks/>
		public string Fax
		{
			get
			{
				return this.faxField;
			}
			set
			{
				this.faxField = value;
			}
		}

		/// <remarks/>
		public string IBAN
		{
			get
			{
				return this.iBANField;
			}
			set
			{
				this.iBANField = value;
			}
		}

		/// <remarks/>
		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public string OrganisationNumber
		{
			get
			{
				return this.organisationNumberField;
			}
			set
			{
				this.organisationNumberField = value;
			}
		}

		/// <remarks/>
		public string OurReference
		{
			get
			{
				return this.ourReferenceField;
			}
			set
			{
				this.ourReferenceField = value;
			}
		}

		/// <remarks/>
		public string OurCustomerNumber
		{
			get
			{
				return this.ourCustomerNumberField;
			}
			set
			{
				this.ourCustomerNumberField = value;
			}
		}

		/// <remarks/>
		public string PG
		{
			get
			{
				return this.pgField;
			}
			set
			{
				this.pgField = value;
			}
		}

		/// <remarks/>
		public string Phone1
		{
			get
			{
				return this.phone1Field;
			}
			set
			{
				this.phone1Field = value;
			}
		}

		/// <remarks/>
		public string Phone2
		{
			get
			{
				return this.phone2Field;
			}
			set
			{
				this.phone2Field = value;
			}
		}

		/// <remarks/>
		public string PreDefinedAccount
		{
			get
			{
				return this.preDefinedAccountField;
			}
			set
			{
				this.preDefinedAccountField = value;
			}
		}

		/// <remarks/>
		public string Project
		{
			get
			{
				return this.projectField;
			}
			set
			{
				this.projectField = value;
			}
		}

		/// <remarks/>
		public string SupplierNumber
		{
			get
			{
				return this.supplierNumberField;
			}
			set
			{
				this.supplierNumberField = value;
			}
		}

		/// <remarks/>
		public string TermsOfPayment
		{
			get
			{
				return this.termsOfPaymentField;
			}
			set
			{
				this.termsOfPaymentField = value;
			}
		}

		/// <remarks/>
		public string VATNumber
		{
			get
			{
				return this.vATNumberField;
			}
			set
			{
				this.vATNumberField = value;
			}
		}

		/// <remarks/>
		public string VisitingAddress
		{
			get
			{
				return this.visitingAddressField;
			}
			set
			{
				this.visitingAddressField = value;
			}
		}

		/// <remarks/>
		public string VisitingCity
		{
			get
			{
				return this.visitingCityField;
			}
			set
			{
				this.visitingCityField = value;
			}
		}

        /// <summary>This field is Read-Only in Fortnox</summary>
        [System.ComponentModel.ReadOnly(true)]
		public string VisitingCountry
		{
			get
			{
				return this.visitingCountryField;
			}
			set
			{
				this.visitingCountryField = value;
			}
		}

		/// <remarks/>
		public string VisitingCountryCode
		{
			get
			{
				return this.visitingCountryCodeField;
			}
			set
			{
				this.visitingCountryCodeField = value;
			}
		}

		/// <remarks/>
		public string VisitingZipCode
		{
			get
			{
				return this.vistingZipCodeField;
			}
			set
			{
				this.vistingZipCodeField = value;
			}
		}

		/// <remarks/>
		public string WorkPlace
		{
			get
			{
				return this.workPlaceField;
			}
			set
			{
				this.workPlaceField = value;
			}
		}

		/// <remarks/>
		public string WWW
		{
			get
			{
				return this.wWWField;
			}
			set
			{
				this.wWWField = value;
			}
		}

		/// <remarks/>
		public string YourReference
		{
			get
			{
				return this.yourReferenceField;
			}
			set
			{
				this.yourReferenceField = value;
			}
		}

		/// <remarks/>
		public string ZipCode
		{
			get
			{
				return this.zipCodeField;
			}
			set
			{
				this.zipCodeField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string url
		{
			get
			{
				return this.urlField;
			}
			set
			{
				this.urlField = value;
			}
		}
	}
}