//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5472
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using FortnoxAPILibrary.Connectors;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class TaxReduction
	{

		private string approvedAmountField;

		private string askedAmountField;

		private string billedAmountField;

		private string customerNameField;

		private string idField;

		private string propertyDesignationField;

		private TaxReductionConnector.ReferenceDocumentType referenceDocumentTypeField;

		private string referenceNumberField;

		private string requestSentField;

		private string residenceAssociationOrganisationNumberField;

		private string socialSecurityNumberField;

		private TaxReductionConnector.TypeOfReduction typeOfReductionField;

		private string voucherNumberField;

		private string voucherSeriesField;

		private string voucherYearField;

		private string urlField;

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string ApprovedAmount
		{
			get
			{
				return this.approvedAmountField;
			}
			set
			{
				this.approvedAmountField = value;
			}
		}

		/// <remarks/>
		public string AskedAmount
		{
			get
			{
				return this.askedAmountField;
			}
			set
			{
				this.askedAmountField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string BilledAmount
		{
			get
			{
				return this.billedAmountField;
			}
			set
			{
				this.billedAmountField = value;
			}
		}

		/// <remarks/>
		public string CustomerName
		{
			get
			{
				return this.customerNameField;
			}
			set
			{
				this.customerNameField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		public string PropertyDesignation
		{
			get
			{
				return this.propertyDesignationField;
			}
			set
			{
				this.propertyDesignationField = value;
			}
		}

		/// <remarks/>
		public TaxReductionConnector.ReferenceDocumentType ReferenceDocumentType
		{
			get
			{
				return this.referenceDocumentTypeField;
			}
			set
			{
				this.referenceDocumentTypeField = value;
			}
		}

		/// <remarks/>
		public string ReferenceNumber
		{
			get
			{
				return this.referenceNumberField;
			}
			set
			{
				this.referenceNumberField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string RequestSent
		{
			get
			{
				return this.requestSentField;
			}
			set
			{
				this.requestSentField = value;
			}
		}

		/// <remarks/>
		public string ResidenceAssociationOrganisationNumber
		{
			get
			{
				return this.residenceAssociationOrganisationNumberField;
			}
			set
			{
				this.residenceAssociationOrganisationNumberField = value;
			}
		}

		/// <remarks/>
		public string SocialSecurityNumber
		{
			get
			{
				return this.socialSecurityNumberField;
			}
			set
			{
				this.socialSecurityNumberField = value;
			}
		}

		/// <remarks/>
		public TaxReductionConnector.TypeOfReduction TypeOfReduction
		{
			get
			{
				return this.typeOfReductionField;
			}
			set
			{
				this.typeOfReductionField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string VoucherNumber
		{
			get
			{
				return this.voucherNumberField;
			}
			set
			{
				this.voucherNumberField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string VoucherSeries
		{
			get
			{
				return this.voucherSeriesField;
			}
			set
			{
				this.voucherSeriesField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string VoucherYear
		{
			get
			{
				return this.voucherYearField;
			}
			set
			{
				this.voucherYearField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string url
		{
			get
			{
				return this.urlField;
			}
			set
			{
				this.urlField = value;
			}
		}
	}
}