//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5472
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
using System;
using FortnoxAPILibrary.Connectors;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Voucher
	{

		private string commentsField;

		private string costCenterField;

		private string descriptionField;

		private string projectField;

		private string referenceNumberField;

		private string referenceTypeField;

		private string transactionDateField;

		private string voucherNumberField;

		private List<VoucherRow> voucherRowsField;

		private string voucherSeriesField;

		private string yearField;

		private string urlField;

        /// <remarks/>
        public Voucher()
        {
            this.VoucherRows = new List<VoucherRow>();
        }

		/// <remarks/>
		public string Comments
		{
			get
			{
				return this.commentsField;
			}
			set
			{
				this.commentsField = value;
			}
		}

		/// <remarks/>
		public string CostCenter
		{
			get
			{
				return this.costCenterField;
			}
			set
			{
				this.costCenterField = value;
			}
		}

		/// <remarks/>
		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		public string Project
		{
			get
			{
				return this.projectField;
			}
			set
			{
				this.projectField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string ReferenceNumber
		{
			get
			{
				return this.referenceNumberField;
			}
			set
			{
				this.referenceNumberField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string ReferenceType
		{
			get
			{
				return this.referenceTypeField;
			}
			set
			{
				this.referenceTypeField = value;
			}
		}

		/// <remarks/>
		public string TransactionDate
		{
			get
			{
				return this.transactionDateField;
			}
			set
			{
				this.transactionDateField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string VoucherNumber
		{
			get
			{
				return this.voucherNumberField;
			}
			set
			{
				this.voucherNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("VoucherRow", IsNullable = false)]
		public List<VoucherRow> VoucherRows
		{
			get
			{
				return this.voucherRowsField;
			}
			set
			{
				this.voucherRowsField = value;
			}
		}

		/// <remarks/>
		public string VoucherSeries
		{
			get
			{
				return this.voucherSeriesField;
			}
			set
			{
				this.voucherSeriesField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string Year
		{
			get
			{
				return this.yearField;
			}
			set
			{
				this.yearField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string url
		{
			get
			{
				return this.urlField;
			}
			set
			{
				this.urlField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class VoucherRow
	{

		private string accountField;

		private string descriptionField;

		private string debitField;

		private string costCenterField;

		private string creditField;

		private string projectField;
        
        private string quantityField;

		private string removedField;

		private string transactionInformationField;

		/// <remarks/>
		public string Account
		{
			get
			{
				return this.accountField;
			}
			set
			{
				this.accountField = value;
			}
		}

		/// <remarks/>
		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		public string Debit
		{
			get
			{
				return this.debitField;
			}
			set
			{
				this.debitField = value;
			}
		}

		/// <remarks/>
		public string CostCenter
		{
			get
			{
				return this.costCenterField;
			}
			set
			{
				this.costCenterField = value;
			}
		}

		/// <remarks/>
		public string Credit
		{
			get
			{
				return this.creditField;
			}
			set
			{
				this.creditField = value;
			}
		}

		/// <remarks/>
		public string Project
		{
			get
			{
				return this.projectField;
			}
			set
			{
				this.projectField = value;
			}
		}

        /// <remarks/>
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }

		/// <summary>This field is Read-Only in Fortnox</summary>
		[System.ComponentModel.ReadOnly(true)]
		public string Removed
		{
			get
			{
				return this.removedField;
			}
			set
			{
				this.removedField = value;
			}
		}

		/// <remarks/>
		public string TransactionInformation
		{
			get
			{
				return this.transactionInformationField;
			}
			set
			{
				this.transactionInformationField = value;
			}
		}
	}
}