//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5472
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.ComponentModel;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace FortnoxAPILibrary
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class VoucherFileConnection
	{

		private string fileIdField;

		private string voucherDescriptionField;

		private string voucherNumberField;

		private string voucherSeriesField;

		private string voucherYearField;

		private string urlField;

		/// <remarks/>
		public string FileId
		{
			get
			{
				return this.fileIdField;
			}
			set
			{
				this.fileIdField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string VoucherDescription
		{
			get
			{
				return this.voucherDescriptionField;
			}
			set
			{
				this.voucherDescriptionField = value;
			}
		}

		/// <remarks/>
		public string VoucherNumber
		{
			get
			{
				return this.voucherNumberField;
			}
			set
			{
				this.voucherNumberField = value;
			}
		}

		/// <remarks/>
		public string VoucherSeries
		{
			get
			{
				return this.voucherSeriesField;
			}
			set
			{
				this.voucherSeriesField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		public string VoucherYear
		{
			get
			{
				return this.voucherYearField;
			}
			set
			{
				this.voucherYearField = value;
			}
		}

		/// <summary>This field is Read-Only in Fortnox</summary>
		[ReadOnly(true)]
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string url
		{
			get
			{
				return this.urlField;
			}
			set
			{
				this.urlField = value;
			}
		}
	}
}