//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortnoxSDK.Tests
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestCredentials
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestCredentials()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FortnoxSDK.Tests.TestCredentials", typeof(TestCredentials).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2f7ec48c-d086-4313-b69f-e2377c880df8.
        /// </summary>
        internal static string Access_Token_OLD
        {
            get
            {
                return ResourceManager.GetString("Access Token OLD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1Pevde6Pls.
        /// </summary>
        internal static string Client_Secret_OLD
        {
            get
            {
                return ResourceManager.GetString("Client Secret OLD", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to 1643810.
        /// </summary>
        internal static string TenantId
        {
            get
            {
                return ResourceManager.GetString("Tenant Id", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to m9ieLg9iVr.
        /// </summary>
        internal static string ClientSecret
        {
            get
            {
                return ResourceManager.GetString("Client Secret", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to c9dHlT04sZNp.
        /// </summary>
        internal static string ClientId
        {
            get
            {
                return ResourceManager.GetString("Client Id", resourceCulture);
            }
        }
    }
}
